### ISSUE TITLE
Make real Slurm nodes to be able to run a test job

### ISSUE THREAD

**Issue by iamtroy412** [pitt-crc/Slurm-Test-Environment#118]
There is a way in Slurm to have one `slurmd` represent a cluster of nodes and be able to run jobs etc against it.

https://slurm.schedmd.com/programmer_guide.html#Tricks-of-the-Trade

This requires us to rebuild the packages with the `--enable-front-end` option.

**Comment by iamtroy412** [comment]
Also worth add `--enable-multiple-slurmd` when rebuilding the packages to enable multiple `slurmd` to run on a single node.

**Comment by djperrefort** [comment]
If you are rebuilding the rpms anyways, it might be worth tackling #116 at the same time.

**Comment by djperrefort** [comment]
@iamtroy412 / @buttermutter I remember discussing in person whether we wanted to implement this. Did we decide to pursue this or close the issue as a "we'll implement i if we ever need it".

**Comment by iamtroy412** [comment]
We'll implement it if we ever need it. As of now, just being able to show the nodes via `sinfo` is good enough. If we ever need to say run a small example job, we'll implement this.

For future ref: https://slurm.schedmd.com/faq.html#multi_slurmd
