### ISSUE TITLE
Switch to rpm install for slurm

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/Slurm-Test-Environment#14]
@buttermutter pointed out Slurm can be installed in a way that is simpler and more in sync with how we do things in production.
Quoting from the [slurm docs](https://slurm.schedmd.com/quickstart_admin.html):

```
NOTE: Items 3 through 8 can be replaced with

    rpmbuild -ta slurm*.tar.bz2
    rpm --install <the rpm files>
```

**Comment by djperrefort** [comment]
I've created a version of the dockerfile using `rpmbuild` and opened a draft PR so that the CI will build the image. A few annoying things:
1. Unless I'm looking in the wrong place, Slurm doesn't host older versions of the tar files on their site. You have to get them through GitHub.
2. The archives on GitHub are named using dashes (`slurm-22-05-2-1.tar.gz`) which is different than the name of the source file defined by `slurm.spec` (`slurm-20.05.2.tar.bz2`). This causes the following error:

`error: Bad source: /slurm-20.05.2.tar.bz2: No such file or directory`

I could just rename the file, but then I have to do a bunch of messy string formatting in bash to turn `22-05-2-1` into `20.05.2` and reformat `.tar.gz` into `.tar.bz2`. I feel like this is something `rpmbuild` should have a workaround for. 

I feel like I'm either looking in the wrong place or missing an rpm feature. Maybe @buttermutter would know?

**Comment by buttermutter** [comment]
We'll point you to the correct location.

**Comment by djperrefort** [comment]
Reopening until PR is submitted and RPMs are being used.
