### ISSUE TITLE
Add build instructions for creating and adding new slurm rpms

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/Slurm-Test-Environment#26]
PR #23 updated the slurm install procedure to install from rpms. Documentation needs to be added on how to build these files and where to add them in the repo.

The `Creating a New Image` section of the README seems like a good place for this.

**Comment by djperrefort** [comment]
@buttermutter would you be willing to pick this issue up?

**Comment by buttermutter** [comment]
Will do.
