### ISSUE TITLE
sinfo fails for Slurm version 20-11-9-1

### ISSUE THREAD

**Issue by chnixi** [pitt-crc/Slurm-Test-Environment#65]
Running the command 'sinfo -M development' gives the error message "sinfo: error: 'development' can't be reached now, or it is an invalid entry for --cluster.  Use 'sacctmgr list clusters' to see available clusters.", despite the fact that the 'development' cluster has been initialized and clearly exists in the rest environment. Only occurs for Slurm version 20-11-9-1.

**Comment by djperrefort** [comment]
@Comeani and @chnixi I just realized there may be a typo in the slurm configuration for this version. Line 178 in `slurm.conf` reads:

```
NodeName=c RealMemory=1000
```

I think it should read

```
NodeName=c[1-10] RealMemory=1000
```

We should see if updating the configuration fixes the issue.

**Comment by Comeani** [comment]
This was a commonly reported fix when I did some googling. The entry point update is still a good addition but I'll test with this first.
