### ISSUE TITLE
Image build test gives false positive

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/Slurm-Test-Environment#7]
Here is an [example build](https://github.com/pitt-crc/Slurm-Test-Environment/runs/7846179121?check_suite_focus=true#step:8:17).

When the image instantiates it gives the following error:

```
slurmdbd: fatal: slurmdbd.conf file /etc/slurm/slurmdbd.conf should be 600 is 644 accessible for group or others
```

However, the CI test to make sure Slurm is installed passes (even though it should fail)

```
Launching sql server...
220815 21:10:24 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
220815 21:10:24 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
Creating Slurm account database
Finished creating database
Create munge key...
Generating a pseudo-random key using /dev/urandom completed.
Starting munge...
Starting slurmdbd...
slurmdbd: fatal: slurmdbd.conf file /etc/slurm/slurmdbd.conf should be 600 is 644 accessible for group or others
slurm 20.11.9
```

**Comment by iamtroy412** [comment]
> When the image instantiates it gives the following error:
> 
> ```
> slurmdbd: fatal: slurmdbd.conf file /etc/slurm/slurmdbd.conf should be 600 is 644 accessible for group or others
> ```

This was fixed in PR #10, we are now setting the file perms when copying the file in the docker image



> 
> However, the CI test to make sure Slurm is installed passes (even though it should fail)
> 
> ```
> Launching sql server...
> 220815 21:10:24 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
> 220815 21:10:24 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
> Creating Slurm account database
> Finished creating database
> Create munge key...
> Generating a pseudo-random key using /dev/urandom completed.
> Starting munge...
> Starting slurmdbd...
> slurmdbd: fatal: slurmdbd.conf file /etc/slurm/slurmdbd.conf should be 600 is 644 accessible for group or others
> slurm 20.11.9
> ```

As far as the false positive goes - Still digging why the error from trying to start up `slurmdbd` is not not failing this step. Also, need to have some other slurm test commands to make sure that all of the services are running correctly. ie `slurmdbd` connection, `slurmctld`
