### ISSUE TITLE
Link mock account creation with list specified in settings.py of bank

### ISSUE THREAD

**Issue by chnixi** [pitt-crc/Slurm-Test-Environment#72]
Right now, in order to add a new Slurm user account for testing the banking system, it is not sufficient to just edit the list in the settings.py file. It would be good to link the list provided in settings.py to the Slurm test environment so that all test accounts listed there are also automatically created here.

**Comment by djperrefort** [comment]
Summarizing an offline discussion:

Keeping the values up to sync is a mild inconvenience, but we expect updates to names in the test environment to happen infrequently. Setting up synchronization infrastructure is likely not worth the time. However, we may revisit this idea should the issue become a more significant problem moving forward.
