### ISSUE TITLE
slurmctld status loop has no sentinel

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/Slurm-Test-Environment#82]
The entry point script waits for `slurmctld` to start up with the following loop:

`until scontrol ping | grep UP; do sleep 3; done`

I was doing some development and accidentally broke the `slurmctld` install. This meant the above loop ran forever. A timeout value should be put in place to avoid infinity hanging entry point evaluations.

**Comment by djperrefort** [comment]
@Comeani are you available to handle this issue?

**Comment by Comeani** [comment]
Can do, thanks for the heads-up.

**Comment by Comeani** [comment]
Closed by #84
